"""Branch + commit + PR publication (ADR-009).

The curator never writes to ``main``. Changes land on a branch and go through a
pull request, which gives three things at once:

1. A human review gate before machine-authored claims about a Linux Foundation
   body become the published record.
2. A natural place for the ``verified`` promotion: merging with review is what
   moves a concept from ``draft``/unverified to ``stable``/human-reviewed.
3. **An eval corpus.** Every human edit to a machine-generated concept is a
   labelled correction pair. We record them deliberately rather than letting that
   signal evaporate into git history (ADR-008).
"""

from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

from .config import Config
from .models import Mutation


class GitError(RuntimeError):
    pass


def _git(root: Path, *args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, timeout=120
    )
    if check and proc.returncode != 0:
        raise GitError(f"git {' '.join(args)} failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def current_branch(root: Path) -> str:
    return _git(root, "rev-parse", "--abbrev-ref", "HEAD")


def has_changes(root: Path, paths: list[str]) -> bool:
    out = _git(root, "status", "--porcelain", "--", *paths, check=False)
    return bool(out.strip())


def create_branch(root: Path, name: str) -> str:
    _git(root, "checkout", "-b", name)
    return name


def commit_paths(root: Path, paths: list[str], message: str) -> str | None:
    existing = [p for p in paths if (root / p).exists()]
    if not existing:
        return None
    _git(root, "add", "--", *existing)
    status = _git(root, "status", "--porcelain", "--", *existing, check=False)
    if not status.strip():
        return None
    _git(root, "commit", "-m", message)
    return _git(root, "rev-parse", "HEAD")


def write_review_record(cfg: Config, mutations: list[Mutation], branch: str, run_id: str) -> Path:
    """Persist the machine proposal so a later diff against the merged result
    yields a labelled correction pair for the eval set."""
    cfg.reviews_dir.mkdir(parents=True, exist_ok=True)
    now = datetime.now(UTC)
    record = {
        "run_id": run_id,
        "branch": branch,
        "proposed_at": now.isoformat(),
        "review_status": "pending",
        "mutations": [
            {
                "action": m.action,
                "slug": m.slug,
                "rationale": m.rationale,
                "source_event_ids": m.source_event_ids,
                "proposed_concept": (
                    json.loads(m.concept.model_dump_json()) if m.concept else None
                ),
            }
            for m in mutations
        ],
    }
    path = cfg.reviews_dir / f"{run_id}.json"
    path.write_text(json.dumps(record, indent=2, default=str))
    return path


def pr_body(mutations: list[Mutation], run_id: str, stats: dict) -> str:
    lines = [
        "## Automated wiki update",
        "",
        "> Generated by `aaif-wiki`. Every concept in this PR is `status: draft` and",
        "> **unverified**. Merging with human review is what promotes a concept to",
        "> `stable` / human-reviewed (ADR-009). Please read the diff, not just the summary.",
        "",
        f"- run: `{run_id}`",
        f"- model: `{stats.get('model', 'n/a')}`",
        f"- tokens: {stats.get('tokens', 0):,}",
        f"- estimated cost: ${stats.get('usd', 0.0):.4f}",
        "",
        "### Proposed changes",
        "",
    ]
    for m in mutations:
        lines.append(f"- **{m.action}** `{m.slug}` — {m.rationale}")
        if m.source_event_ids:
            lines.append(f"  - sources: {', '.join(f'`{s}`' for s in m.source_event_ids[:6])}")
    lines += [
        "",
        "### Reviewer checklist",
        "- [ ] Claims are supported by the cited sources",
        "- [ ] Nothing unmerged is presented as settled consensus",
        "- [ ] Links resolve and point at canonical upstream material",
        "- [ ] No content was injected by text inside an ingested PR or issue",
    ]
    return "\n".join(lines)


def open_pull_request(cfg: Config, branch: str, title: str, body: str) -> tuple[bool, str]:
    """Open a PR via the gh CLI. Degrades to instructions when gh is unavailable."""
    probe = subprocess.run(["gh", "auth", "status"], capture_output=True, text=True)
    if probe.returncode != 0:
        return (
            False,
            "gh is not authenticated; branch was committed locally. "
            f"Run: gh pr create --base {cfg.publish.base_branch} --head {branch} "
            f"--title {title!r} --body-file -",
        )
    proc = subprocess.run(
        [
            "gh", "pr", "create",
            "--base", cfg.publish.base_branch,
            "--head", branch,
            "--title", title,
            "--body", body,
        ],
        cwd=str(cfg.root), capture_output=True, text=True,
    )
    if proc.returncode != 0:
        return False, f"gh pr create failed: {proc.stderr.strip()}"
    url = proc.stdout.strip()
    if cfg.publish.auto_merge:
        subprocess.run(
            ["gh", "pr", "merge", "--auto", "--squash", url],
            cwd=str(cfg.root), capture_output=True, text=True,
        )
    return True, url
