"""Executive digest exporter.

Two rules that come straight from ADR-009 and ADR-010 and are enforced in code,
not left to operator discipline:

* **Only human-reviewed content is published.** Draft and unverified concepts
  never leave the repository. The digest is a public statement about a Linux
  Foundation body; machine-inferred claims do not qualify.
* **Every digest carries the unofficial disclaimer.**
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

from ..models import ConceptStatus
from ..okf import load_bundle
from .base import BaseExporter, ExportResult

DISCLAIMER = """\
> **Unofficial.** This digest is generated by `aaif-wiki`, a personal open-source
> project. It is **not** endorsed by, affiliated with, or an official communication
> of the Agentic AI Foundation or the Linux Foundation. All content is derived from
> public sources; follow the links for canonical material.
"""


class GistExporter(BaseExporter):
    name = "gist"

    def export(self) -> ExportResult:
        concepts = load_bundle(self.cfg.bundle_dir)

        publishable = [
            c
            for c in concepts.values()
            if c.status is ConceptStatus.STABLE and c.trust_tier == "human-reviewed"
        ]
        withheld = len(concepts) - len(publishable)

        if not publishable:
            return ExportResult(
                ok=True,
                message=(
                    f"nothing publishable: {withheld} concept(s) are draft or unverified. "
                    "Human review promotes concepts to stable (ADR-009)."
                ),
            )

        blocked = self.guard(publishable)
        if blocked:
            return ExportResult(ok=False, blocked=blocked, message="leak guard blocked digest")

        today = datetime.now(UTC).date().isoformat()
        lines = [
            f"# AAIF Knowledge Digest — {today}",
            "",
            DISCLAIMER,
            "",
            f"{len(publishable)} reviewed concept(s). {withheld} withheld pending review.",
            "",
        ]
        by_type: dict[str, list] = {}
        for c in publishable:
            by_type.setdefault(c.type, []).append(c)
        for ctype, group in sorted(by_type.items()):
            lines.append(f"## {ctype}")
            for c in sorted(group, key=lambda x: x.title):
                link = c.resource or ""
                suffix = f" — [source]({link})" if link else ""
                lines.append(f"- **{c.title}** — {c.description}{suffix}")
            lines.append("")

        body = self.sanitize("\n".join(lines))
        out_dir: Path = self.cfg.dist_dir
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / f"digest-{today}.md"
        path.write_text(body)

        return ExportResult(
            ok=True,
            artifacts=[path],
            message=f"digest written ({len(publishable)} concepts, {withheld} withheld)",
        )
